/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-03-03 06:42:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajaxtest6_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h3>Ajax test</h3>\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<th>이름<th/>\r\n");
      out.write("\t\t\t<th>나이<th/>\r\n");
      out.write("\t\t\t<th>주소<th/>\r\n");
      out.write("\t\t<thead/>\r\n");
      out.write("\t\t<tbody id=\"tbody\">\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\tgoJSON();\r\n");
      out.write("}\r\n");
      out.write("\tfunction goJSON(){\r\n");
      out.write("\t\t//1.객체를 만든다\r\n");
      out.write("\t\tvar xhttp=new XMLHttpRequest();\r\n");
      out.write("\t\txhttp.onreadystatechange = function(){\r\n");
      out.write("\t\t\tconsole.log(\"readyState : \", this.readyState, \"   status:\", this.status);\r\n");
      out.write("\t\t\tif(this.readyState ==4 && this.status == 200){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar tbody = document.getElementById(\"tbody\");\r\n");
      out.write("\t\t\t\tvar data = JSON.parse(this.responseText);// string-> JSON객체로 변환\r\n");
      out.write("\t\t\t\tfor(i=0;i<data.length;i++)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar row=tbody.insertRow(tbody.rows.length);\r\n");
      out.write("\t\t\t\t\tvar cell1 = row.insertCell(0);\r\n");
      out.write("\t\t\t\t\tvar cell2 = row.insertCell(1);\r\n");
      out.write("\t\t\t\t\tvar cell3 = row.insertCell(2);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcell1.innerHTML = data[i].name;\r\n");
      out.write("\t\t\t\t\tcell2.innerHTML = data[i].age;\r\n");
      out.write("\t\t\t\t\tcell3.innerHTML = data[i].address;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tconsole.log(data[i].name);\r\n");
      out.write("\t\t\t\tconsole.log(data[i].age);\r\n");
      out.write("\t\t\t\tconsole.log(data[i].phone);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("// \t\t\t\tdocument.getElementById(\"result\").innerHTML=\"이름\"+data.name+\"<br>\"\r\n");
      out.write("// \t\t\t\t+\"나이:\" + data.age + \"<br/>\"\r\n");
      out.write("// \t\t\t\t+\"전화:\" + data.phone+\"<br/>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar url = \"/myhome/data2.jsp\";\r\n");
      out.write("\t\tconsole.log(url);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txhttp.open(\"GET\",url,true);\r\n");
      out.write("\t\txhttp.send();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
